### ISSUE TITLE
Add support for missing languages

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#2]
These languages are currently missing from the app, despite geolexica-database containing them:

* Dutch
* Finnish
* Japanese
* Polish

**Comment by strogonoff** [comment]
For the record, I am migrating to dynamic language definition altogether. Expect to address this in the next release (alpha 10).

**Comment by ronaldtse** [comment]
Excellent, look forward to it!

**Comment by ronaldtse** [comment]
@strogonoff this is not fixed, right?

**Comment by strogonoff** [comment]
Not yet, estimating today

**Comment by strogonoff** [comment]
Finnish
Japanese
Polish

These three are in the app, aren’t they? Dutch will appear in the new release.

**Comment by ronaldtse** [comment]
Yes they are. Thanks!

**Comment by strogonoff** [comment]
This was fixed in https://github.com/glossarist/glossarist-desktop/commit/2096a0f0e9fd09f5fdda1a52faf5e1d338a87838, https://github.com/glossarist/glossarist-desktop/commit/83665503d1e8e1cb8eab7bd4a73436554662887b, https://github.com/glossarist/glossarist-desktop/commit/9de2198d914c83ff1f0a98ce8de9ed1773e42ae7, https://github.com/glossarist/glossarist-desktop/commit/d2166e38d8670a4b939964d6c3d8c864895dcd6c
