### ISSUE TITLE
In Translate tab, "Domain" is not legacy

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#44]
Domain and Usage notes are both allowed. Both can co-exist. Usage notes is used in IEV, but all other ISO terms use Domain.

Domain is the "<...>" thing in the Designation.

**Comment by strogonoff** [comment]
@ronaldtse per earlier discussion while working on IEC dataset, we are modeling domain as a type of hierarchical concept relationship. If there is a related concept, it will be shown in the <…> brackets. For existing legacy domains, they will be migrated this way and requisite relationships added.

**Comment by strogonoff** [comment]
It can be made editable though, if it needs to be edited before we do said migration.

**Comment by ronaldtse** [comment]
> If there is a related concept, it will be shown in the <…> brackets. For existing legacy domains, they will be migrated this way and requisite relationships added.

How are we going to make this migration? There are many terms now that have domain embedded in the designation.

**Comment by strogonoff** [comment]
@ronaldtse 

> How are we going to make this migration? There are many terms now that have domain embedded in the designation.

1. There already exists migration logic that moves the domain(s) out of designation into a separate field of the concept entity. That would be step 1.

2. This step might not be fully automatic. It would require locating the concept(s) referenced by the domain(s), and creating a relationship with each of the domains.

  Before step (2) is done, the app and/or Geolexica HTML rendering would have to be updated so that domain is taken based on relationships.

**Comment by strogonoff** [comment]
Filed the issue to make the Domain field editable in meantime as https://github.com/glossarist/glossarist-desktop/issues/51
