### ISSUE TITLE
"NOTE X" should be "Note X to entry"

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#62]
In ISO and IEC, the label for a NOTE is always "Note X to entry".

According to Jo Goodwin the Terminology Manager of IEC, "Note X to entry" is a *normative* element belonging to the entry. It was intentionally renamed from "NOTE X" to "Note X to entry" to reflect this change. (X is the number of the note).

So all "NOTE" labels we see in the app should be changed to "Note X to entry".

**Comment by strogonoff** [comment]
@ronaldtse 

There are two concerns: (1) software used to edit register/standard, (2) the normative representation of the register (website, PDF, HTML, etc.).

I suspect that the data management UI falls outside normative representation. The normative representation would be some specific deliverable HTML/PDF we generate (from the data managed through that UI).

For example, you wouldn’t care whether or not .adoc files exactly complies with how documents are supposed to look—that would not be expected, you only care if Metanorma later renders them in a compliant way. App UI offers more opportunity to make things “look” normative, but in fact it is the same thing as .adoc file in a Git repo: a way to enter/manipulate data.

I’ll look at rewording the note labels in the app if otherwise UI constraints allow, but I put forward that attempting to bring _app UI_ (rather than deliverables) in line with compliance specifics may be unnecessary effort (and in some other cases may be much more complicated to achieve).

**Comment by ronaldtse** [comment]
I share the same concerns and understand; they are valid. 

That said, in this case, ISO and IEC shares the same nomenclature, so it takes care of potential confusions that users have (several people have raised this "NOTE" issue).

**Comment by strogonoff** [comment]
In order to address this we would have to make a grand overhaul of everything and offer Glossarist UI translated in all supported languages. This does not seem feasible in near future under constraints🤔
