### ISSUE TITLE
(URGENT) New bug 1.5.6/1.5.7. Clicking on Translate automatically switches to Arabic

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#68]
From @strogonoff :
> It switches to the first non-authoritative language by design
> You have to select a non-authoritative language to translate to, if you want to do translation

If you click List (English) > Translate > List, you get a list in Arabic. Which is very confusing.

**Comment by strogonoff** [comment]
(By design)

**Comment by strogonoff** [comment]
After a discussion, the issue is that:

* the app force-selects a non-authoritative language to make Translate module usable (you can’t translate from English into English). The language selected may not match the language translator wants to use.

* after switching to another module from Translate, the app remains in the language used in Translate. (By design, Language context is shared across all modules.)

**Comment by strogonoff** [comment]
This will no longer be an issue when we switch to subregistries for localized entries.

**Comment by strogonoff** [comment]
The confusion possibly arose from the fact that the order of languages changed. Until `register.yaml` was added, the first non-auth language selected by Translate was not noticed since many entries were not translated to that language (or language looked similar enough to English). Now the order of languages has changed, and the first non-auth language is Arabic, which is markedly different from English.

**Comment by ronaldtse** [comment]
Also reported by ISO/TC 211 TMG. This issue is fixed in 1.6.0. Thanks @strogonoff !
